"""
Web Scraping + AI Analysis — A Freelancer's Swiss Army Knife
===============================================================
Scrape any website and use API Shop's DeepSeek/Kimi models to
analyze, summarize, or extract structured data — all in one script.

Perfect for freelancer gigs: data extraction, competitor analysis,
content summarization, lead generation, and more.

API Shop: https://shop.pricepulseapi.site
Freelancer: https://freelancer.com/get/rocks081?f=give
Author: @rock2089
"""

import requests
from bs4 import BeautifulSoup
import json
import sys

API_KEY = "your-api-key"  # Get at https://shop.pricepulseapi.site
API_URL = "https://pricepulseapi.site/v1/chat/completions"

def call_ai(prompt, model="deepseek-v4-flash", max_tokens=500):
    """Call API Shop with any DeepSeek/Kimi model."""
    response = requests.post(
        API_URL,
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_tokens,
            "temperature": 0.3,
        },
        timeout=60,
    )
    return response.json()["choices"][0]["message"]["content"]

def scrape_page(url):
    """Scrape a webpage and return clean text."""
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; APIShopDemo/1.0; +https://shop.pricepulseapi.site)"
    }
    resp = requests.get(url, headers=headers, timeout=15)
    soup = BeautifulSoup(resp.text, "html.parser")

    # Remove scripts and styles
    for tag in soup(["script", "style", "nav", "footer", "header"]):
        tag.decompose()

    text = soup.get_text(separator="\n", strip=True)
    # Clean up whitespace
    lines = [line.strip() for line in text.split("\n") if line.strip()]
    return "\n".join(lines)

# ============================================================
# DEMO 1: Summarize a webpage
# ============================================================
def summarize_url(url):
    """Scrape and summarize any URL in one call."""
    print(f"Scraping: {url[:60]}...")
    content = scrape_page(url)
    # Limit length to avoid token limits
    content = content[:6000]

    print(f"Analyzing with DeepSeek V4...")
    summary = call_ai(
        f"Summarize this webpage content in 3-5 bullet points. "
        f"Be specific and include key facts/numbers:\n\n{content}",
        model="deepseek-v4-flash",
        max_tokens=300,
    )
    return summary

# ============================================================
# DEMO 2: Extract structured data (e.g., product listings)
# ============================================================
def extract_structured_data(html_content, schema_description):
    """Use AI to extract structured JSON from scraped HTML."""
    prompt = f"""Extract {schema_description} from this HTML text content.
Return ONLY valid JSON. No explanation, no markdown fences.

Content:
{html_content[:5000]}
"""
    result = call_ai(prompt, model="deepseek-v4-pro", max_tokens=800)
    try:
        return json.loads(result)
    except json.JSONDecodeError:
        # Try to extract JSON from the response
        import re
        match = re.search(r"\[.*\]|\{.*\}", result, re.DOTALL)
        if match:
            return json.loads(match.group())
        return {"raw": result}

# ============================================================
# DEMO 3: Freelancer project idea generator
# ============================================================
def generate_project_ideas(skill="Python automation"):
    """Generate freelancer project ideas you can bid on."""
    prompt = f"""I am a freelancer skilled in {skill}.
Give me 5 specific project ideas I could offer on platforms like Freelancer.com.
For each, include: title, one-line description, estimated price ($50-500),
and required tools. Be practical and specific."""
    return call_ai(prompt, model="deepseek-v4-flash", max_tokens=500)

# ============================================================
# RUN DEMOS
# ============================================================
if __name__ == "__main__":
    # Demo 3: Generate project ideas (no scraping needed)
    print("=" * 60)
    print("Freelancer Project Ideas (generated by API Shop)")
    print("=" * 60)
    ideas = generate_project_ideas("Python web scraping, data extraction, Excel automation")
    print(ideas)

    # Demo 1: Scrape & summarize (if URL provided)
    if len(sys.argv) > 1:
        url = sys.argv[1]
        print("\n" + "=" * 60)
        print(f"Summary of {url}")
        print("=" * 60)
        summary = summarize_url(url)
        print(summary)
    else:
        print("\nTip: Pass a URL to scrape and summarize!")
        print("   python scraper_ai_demo.py https://example.com")

    print("\n---")
    print("Get your API key: https://shop.pricepulseapi.site")
    print("Hire me: https://freelancer.com/get/rocks081?f=give")
